org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Kotlin/Gradle: на Windows иногда падает инкрементальная компиляция из-за путей
# к кэшу (Pub Cache) и рабочему каталогу на разных "root".
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
